version: "3.10"
services:
  web:
    depends_on:
      - db
    build:
      context: ./web
      dockerfile: Dockerfile
    image: django-kub8
    environment:
      - PORT=8020
    env_file:
      - web/.env
    ports:
      - "8001:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
  db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - web/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - db_data:/var/lib/postgresql/data/
  redis_db:
    image: redis
    restart: always
    expose:
      - 6388
    ports:
      - "6388:6388"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380

volumes:
  staticfiles:
    external: true
  db_data:
  redis_data: