apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV5TURJeApOVEF3TXpkYUZ3MDBNakV5TURJeE5UQXdNemRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEaTNYUEQ0MXJsWnFMMHNZV2ZUMnBVbzFDajVBUlkwRXJPSmF2SlBRNk1vbm9EVjdrbwpXck43YUUvaFp2eVlBMEd6MnBxYlR0OVZGb1kxT1gwQUpBb2VPeVRkVkpsYTVYU3dWRGtjTkZwM0ZGN1JpN0NhCm1vRlBhZFQxUVMvMFlhQmE3T0UrVTg2cUVuQXduZ3hoTjFUUE1mdlo4RTlpbVdHd25mZ0dHQkY0NlNNT1greVIKYklMeUlVSDBBY0NrUGlUV3NLSHNjTXVSK29XUyswNS81ZkttZDNEQjNrYWhEVHhJYkNSMktnaFN5RHRSeVZVYQpxSDJaYUtCMDN5ZUtsS2R1WUJSMkJnSE52a0NqYWhHRjg4TktZbEVrU0F3MnQ4Zmo2RjBUYWwySjd0RXlwUjJWCmRVbWtDdnVtWXlyK08yZEk4SWdPRjV5MUJTRXdkM1BFWmwwdEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlN3VU1jamdUcG4ybFRFK2k4Qgo1bnZyMllZOEhUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtMnI2QmJjWFU5N1BwT3dueGxmckNNSGdlQXlpCjNWc2oxVlI1QlZwRUJpYmNoeXNzdnFZUVN2aHI1UGNUMDFiSjhEbWxtdjlqMm1jdE42ODY1VG1MeFcrcHMvdkIKOUNITnZjQkdJeWpscVFDdnIvVkhZY05vaEluL2lhTXBtWnl2QjcxVnVvbGlPeE9CVjYrV0dsUEwrQk9XMUxnMApHam5nbFViYlpoNGJUMFY3dTN0eUZkbWpFQlYwd1c3bDhYdEhOeXovaXI1Uzh6UGZQYlFaQXh1VzV2c1ZvUVBqCkR6VlBHakdHc2hHRU1WOURUcnlCaTFxdzVRTDNheDZ3MGNBVUFNRmxvK3l4VXFMWDY1MUpmYmJ4UnQyVDBSLzQKcWpkQ2FOSk9lenV3WXhsRWo5Q3c0VnhXalVHS2lwTFlBUkZkd0RtQ3BveFVWUTl1L0RxbzR6azljdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://d30017b2-75fb-4fec-bca7-8886dbc76a6a.k8s.ondigitalocean.com
  name: do-ams3-django-k8s
contexts:
- context:
    cluster: do-ams3-django-k8s
    user: do-ams3-django-k8s-admin
  name: do-ams3-django-k8s
current-context: do-ams3-django-k8s
kind: Config
preferences: {}
users:
- name: do-ams3-django-k8s-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=default
      - d30017b2-75fb-4fec-bca7-8886dbc76a6a
      command: doctl
      env: null
      provideClusterInfo: false
