name: Build Docker Container & Push to The Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  django_testing_job:
    uses: MDRCS/django-kub8/.github/workflows/ci.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [django_testing_job]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_REGISTRY_TOKEN_API }}
    - name: Login to Digital Ocean Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
    - name: Build Container Image
      working-directory: ./web
      run: |
        docker build -f Dockerfile \
          -t registry.digitalocean.com/private-registery/django-kub8:latest \
          -t registry.digitalocean.com/private-registery/django-kub8:${GITHUB_SHA::7} \
          .
    - name: Push Image
      run: |
        docker push registry.digitalocean.com/private-registery/django-kub8 --all-tags


      
        
      
