name: Build Docker Container & Push to The Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  django_testing_job:
    uses: MDRCS/django-kub8/blob/main/.github/workflows/ci.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [django_testing_job]
    steps:
    - uses: actions/checkout@v3
