name: Build Docker Container & Push to The Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  django_testing_job:
    uses: MDRCS/django-kub8/.github/workflows/ci.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [django_testing_job]
    env:
      CLUSTER_NAME: django-k8s
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_REGISTRY_TOKEN_API }}
    - name: Login to Digital Ocean Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
    - name: Build Container Image
      working-directory: ./web
      run: |
        docker build -f Dockerfile \
          -t registry.digitalocean.com/private-registery/django-kub8:latest \
          -t registry.digitalocean.com/private-registery/django-kub8:${GITHUB_SHA::7} \
          .
    - name: Push Image
      run: |
        docker push registry.digitalocean.com/private-registery/django-kub8 --all-tags
    - name: Access to Kubernetes cluster kubeconfig file w/ short-lived credentials
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
    - name: Update deployment secrets
      run: |
        cat << EOF >> web/.env.prod
        DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
        DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        EOF
        kubectl delete secret django-kub8-prod-env
        kubectl create secret generic django-kub8-prod-env --from-env-file=web/.env.prod
    - name: Update Deployment Image
      run: |
        kubectl set image deployment/django-kub8-deployment django-kub8=registry.digitalocean.com/private-registery/django-kub8:${GITHUB_SHA::7}
    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/django-kub8-deployment
    - name: Migrate database Command
      run: |
        export SINGLE_POD_NAME=$(kubectl get pod -l=app=django-kub8-deployment -o NAME | tail -n 1)
        kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh